name: TradePlugin
version: '1.0-SNAPSHOT'
main: com.misagh.tradeplugin.TradePlugin
api-version: '1.20'
load: STARTUP
commands:
  sellhouse:
    description: فروش یک منطقه به بازیکن دیگر.
    usage: /sellhouse <بازیکن> <نام منطقه>
  buyhouse:
    description: خرید یک منطقه از بازیکن دیگر.
    usage: /buyhouse <بازیکن> <نام منطقه>
  tradehouse:
    description: Trade house between players.
    usage: /tradehouse <player> <region> <price>
  tradeDecline:
    description: Trade house between players.
    usage:
  tradeaccept: